name: flutter_zoom_videosdk_example
description: Demonstrates how to use the flutter_zoom_videosdk plugin.
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_zoom_videosdk:
    path: ../

  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.3+1
  dart_jsonwebtoken: ^3.3.1
  google_fonts: ^8.0.1
  events_emitter: ^0.6.0
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  device_info_plus: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/